// sdk/ui/svelte/src/routes/Login.svelte
<script>
    import useId from "../hooks/useId";
    import cssClassAssembler from "../utils/cssClassAssembler";
    import defaultClasses from "./index.module.css";
    const COMPONENT = "sso";
  
    export let onSubmit;
    export let ssoIdentifier = "";
    export let styles;
    export let innerProps;
    export let classNames;
    export let inputLabel = "Tenant";
    export let placeholder = "";
    export let buttonText = "Sign-in with SSO";
  
    function mitosis_styling(node, vars) {
      Object.entries(vars || {}).forEach(([p, v]) => {
        if (p.startsWith("--")) {
          node.style.setProperty(p, v);
        } else {
          node.style[p] = v;
        }
      });
    }
  
    function handleChange(e) {
      errMsg = "";
      ssoIdentifierState = e.currentTarget.value;
    }
    function onSubmitButton(event) {
      void (async function (e) {
        e.preventDefault();
        isProcessing = true;
        const {
          error: { message },
        } = (await onSubmit(ssoIdentifierState || ssoIdentifier)) || {
          error: {},
        };
        isProcessing = false;
        if (typeof message === "string" && message) {
          errMsg = message;
        }
      })(event);
    }
    $: InputId = () => {
      return useId(COMPONENT, "input");
    };
    $: ErrorSpanId = () => {
      return useId(COMPONENT, "span");
    };
  
    let ssoIdentifierState = "";
    let errMsg = "";
    let isProcessing = false;
    let isError = !!errMsg;
  </script>
  
  <div
    use:mitosis_styling={{
      ...styles?.container,
    }}
    {...innerProps?.container}
    class={cssClassAssembler(classNames?.container, defaultClasses.container)}
  >
    {#if !ssoIdentifier}
      <label
        use:mitosis_styling={{
          ...styles?.label,
        }}
        for={InputId()}
        {...innerProps?.label}
        class={cssClassAssembler(classNames?.label, defaultClasses.label)}
      >
        {inputLabel}
      </label>
  
      <input
        use:mitosis_styling={{
          ...styles?.input,
        }}
        id={InputId()}
        value={ssoIdentifierState}
        {placeholder}
        on:input={(event) => {
          handleChange(event);
        }}
        aria-invalid={!!errMsg}
        aria-describedby={ErrorSpanId()}
        {...innerProps?.input}
        class={cssClassAssembler(classNames?.input, defaultClasses.input)}
      />
  
      {#if !!errMsg}
        <span id={ErrorSpanId()}>{errMsg}</span>
      {/if}
    {/if}
    <button
      use:mitosis_styling={{
        ...styles?.button,
      }}
      type="button"
      disabled={!(ssoIdentifierState || ssoIdentifier) || isProcessing}
      on:click={(event) => {
        onSubmitButton(event);
      }}
      {...innerProps?.button}
      class={cssClassAssembler(classNames?.button, defaultClasses.button)}
    >
      {buttonText}
    </button>
  </div>

// sdk/ui/vue/src/Login/login.vue
<template>
    <div
      :style="{
        ...styles?.container,
      }"
      :class="
        _classStringToObject(
          cssClassAssembler(classNames?.container, defaultClasses.container)
        )
      "
      v-bind="innerProps?.container"
    >
      <template v-if="!this.ssoIdentifier">
        <label
          :for="InputId"
          :style="{
            ...styles?.label,
          }"
          :class="
            _classStringToObject(
              cssClassAssembler(classNames?.label, defaultClasses.label)
            )
          "
          v-bind="innerProps?.label"
        >
          {{ inputLabel }}
        </label>
        <input
          :id="InputId"
          :value="ssoIdentifierState"
          :placeholder="placeholder"
          @input="handleChange($event)"
          :style="{
            ...styles?.input,
          }"
          :aria-invalid="!!this.errMsg"
          :aria-describedby="ErrorSpanId"
          :class="
            _classStringToObject(
              cssClassAssembler(classNames?.input, defaultClasses.input)
            )
          "
          v-bind="innerProps?.input"
        />
  
        <template v-if="!!this.errMsg">
          <span :id="ErrorSpanId">{{ errMsg }}</span>
        </template>
      </template>
  
      <button
        type="button"
        :disabled="isButtonDisabled"
        @click="onSubmitButton($event)"
        :style="{
          ...styles?.button,
        }"
        :class="
          _classStringToObject(
            cssClassAssembler(classNames?.button, defaultClasses.button)
          )
        "
        v-bind="innerProps?.button"
      >
        {{ buttonText }}
      </button>
    </div>
  </template>
  
  <script>
  import useId from "../hooks/useId";
  import cssClassAssembler from "../utils/cssClassAssembler";
  import defaultClasses from "./index.module.css";
  const COMPONENT = "sso";
  
  export default {
    name: "login",
  
    props: {
      ssoIdentifier: { default: "" },
     // onSubmit:  default: undefined ,
      styles: { default: undefined },
      errorMessage: { default: {
        error: {
          message: "",
        }
      } },
      innerProps: { default: undefined },
      classNames: { default: undefined },
      inputLabel: { default: "Tenant" },
      placeholder: { default: "" },
      buttonText: { default: "Sign-in with SSO" },
    },
  
    data() {
      return {
        ssoIdentifierState: "",
        errMsg: "",
        isProcessing: false,
        cssClassAssembler,
        defaultClasses,
      };
    },
  
    computed: {
      InputId() {
        return useId(COMPONENT, "input");
      },
      ErrorSpanId() {
        return useId(COMPONENT, "span");
      },
      isButtonDisabled(){
        return  !(this.ssoIdentifierState || this.ssoIdentifier) || this.isProcessing;
      }
    },
  
    methods: {
      handleChange(e) {
        this.errMsg = "";
        this.ssoIdentifierState = e.currentTarget.value;
      },
      onSubmitButton(event) {
        const that = this
        void (async function (e) {
          e.preventDefault();
          that.isProcessing = true;
         (that.$emit('onSubmit',that.ssoIdentifierState || that.ssoIdentifier));
          that.isProcessing = false;
          const { error } = that.errorMessage
          if (typeof error.message === "string" && error.message) {
            that.errMsg = error.message;
          }
        })(event);
      },
      _classStringToObject(str) {
        const obj = {};
        if (typeof str !== "string") {
          return obj;
        }
        const classNames = str.trim().split(/\s+/);
        for (const name of classNames) {
          obj[name] = true;
        }
        return obj;
      },
    },
  };
  </script>
