// sdk/ui/vue/src/Login/index.vue
<template>
  <div
    :style="{
      ...styles?.container,
    }"
    :class="
      _classStringToObject(
        cssClassAssembler(classNames?.container, defaultClasses.container)
      )
    "
    v-bind="innerProps?.container"
  >
    <template v-if="shouldRenderInput">
      <label
        :for="InputId"
        :style="{
          ...styles?.label,
        }"
        :class="
          _classStringToObject(
            cssClassAssembler(classNames?.label, defaultClasses.label)
          )
        "
        v-bind="innerProps?.label"
      >
        {{ inputLabel }}
      </label>
      <input
        :id="InputId"
        :value="ssoIdentifierState"
        :placeholder="placeholder"
        @input="handleChange($event)"
        :style="{
          ...styles?.input,
        }"
        :aria-invalid="isError"
        :aria-describedby="ErrorSpanId"
        :class="
          _classStringToObject(
            cssClassAssembler(classNames?.input, defaultClasses.input)
          )
        "
        v-bind="innerProps?.input"
      />

      <template v-if="isError">
        <span :id="ErrorSpanId">{{ errMsg }}</span>
      </template>
    </template>

    <button
      type="button"
      :disabled="disableButton"
      @click="onSubmitButton($event)"
      :style="{
        ...styles?.button,
      }"
      :class="
        _classStringToObject(
          cssClassAssembler(classNames?.button, defaultClasses.button)
        )
      "
      v-bind="innerProps?.button"
    >
      {{ buttonText }}
    </button>
  </div>
</template>

<script setup>
import { computed, ref } from "vue";

import useId from "../hooks/useId";
import cssClassAssembler from "../utils/cssClassAssembler";
import defaultClasses from "./index.module.css";
const COMPONENT = "sso";

const props = withDefaults(defineProps(), {
  ssoIdentifier: "",
  onSubmit: undefined,
  styles: undefined,
  innerProps: undefined,
  classNames: undefined,
  inputLabel: "Tenant",
  placeholder: "",
  buttonText: "Sign-in with SSO",
});
const ssoIdentifierState = ref("");
const errMsg = ref("");
const isProcessing = ref(false);
const shouldRenderInput = ref(!props.ssoIdentifier);
const isError = ref(!!errMsg.value);
const disableButton = ref(
  !(ssoIdentifierState.value || props.ssoIdentifier) || isProcessing.value
);

const InputId = computed(() => {
  return useId(COMPONENT, "input");
});
const ErrorSpanId = computed(() => {
  return useId(COMPONENT, "span");
});

function handleChange(e) {
  errMsg.value = "";
  ssoIdentifierState.value = e.currentTarget.value;
}
function onSubmitButton(event) {
  void (async function (e) {
    e.preventDefault();
    isProcessing.value = true;
    const {
      error: { message },
    } = (await props.onSubmit(ssoIdentifierState || props.ssoIdentifier)) || {
      error: {},
    };
    isProcessing.value = false;
    if (typeof message === "string" && message) {
      errMsg.value = message;
    }
  })(event);
}
function _classStringToObject(str) {
  const obj = {};
  if (typeof str !== "string") {
    return obj;
  }
  const classNames = str.trim().split(/\s+/);
  for (const name of classNames) {
    obj[name] = true;
  }
  return obj;
}
</script>

// sdk/ui/svelte/src/routes/Login.svelte
<script>
    import useId from "../hooks/useId";
    import cssClassAssembler from "../utils/cssClassAssembler";
    import defaultClasses from "./index.module.css";
    const COMPONENT = "sso";
  
    export let onSubmit;
    export let ssoIdentifier = "";
    export let styles;
    export let innerProps;
    export let classNames;
    export let inputLabel = "Tenant";
    export let placeholder = "";
    export let buttonText = "Sign-in with SSO";
  
    function mitosis_styling(node, vars) {
      Object.entries(vars || {}).forEach(([p, v]) => {
        if (p.startsWith("--")) {
          node.style.setProperty(p, v);
        } else {
          node.style[p] = v;
        }
      });
    }
  
    function handleChange(e) {
      errMsg = "";
      ssoIdentifierState = e.currentTarget.value;
    }
    function onSubmitButton(event) {
      void (async function (e) {
        e.preventDefault();
        isProcessing = true;
        const {
          error: { message },
        } = (await onSubmit(ssoIdentifierState || ssoIdentifier)) || {
          error: {},
        };
        isProcessing = false;
        if (typeof message === "string" && message) {
          errMsg = message;
        }
      })(event);
    }
    $: InputId = () => {
      return useId(COMPONENT, "input");
    };
    $: ErrorSpanId = () => {
      return useId(COMPONENT, "span");
    };
  
    let ssoIdentifierState = "";
    let errMsg = "";
    let isProcessing = false;
    let isError = !!errMsg;
  </script>
  
  <div
    use:mitosis_styling={{
      ...styles?.container,
    }}
    {...innerProps?.container}
    class={cssClassAssembler(classNames?.container, defaultClasses.container)}
  >
    {#if !ssoIdentifier}
      <label
        use:mitosis_styling={{
          ...styles?.label,
        }}
        for={InputId()}
        {...innerProps?.label}
        class={cssClassAssembler(classNames?.label, defaultClasses.label)}
      >
        {inputLabel}
      </label>
  
      <input
        use:mitosis_styling={{
          ...styles?.input,
        }}
        id={InputId()}
        value={ssoIdentifierState}
        {placeholder}
        on:input={(event) => {
          handleChange(event);
        }}
        aria-invalid={!!errMsg}
        aria-describedby={ErrorSpanId()}
        {...innerProps?.input}
        class={cssClassAssembler(classNames?.input, defaultClasses.input)}
      />
  
      {#if !!errMsg}
        <span id={ErrorSpanId()}>{errMsg}</span>
      {/if}
    {/if}
    <button
      use:mitosis_styling={{
        ...styles?.button,
      }}
      type="button"
      disabled={!(ssoIdentifierState || ssoIdentifier) || isProcessing}
      on:click={(event) => {
        onSubmitButton(event);
      }}
      {...innerProps?.button}
      class={cssClassAssembler(classNames?.button, defaultClasses.button)}
    >
      {buttonText}
    </button>
  </div>
