// sdk/ui/angular/projects/docs/src/app/navbar/navbar.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
  selector: 'app-navbar',
  template: `
  <nav class="flex justify-between align-middle px-10 py-2 shadow-sm h-[65px] mb-[15px]">
    <div class="flex justify-center items-center text-[#24292E]">
      <img alt="BoxyHQ logo" src="../assets/logo.png" class="w-10 h-10"/>
      <h1 class="text-[22px] font-serif ml-2 text-[#24292E]">BoxyHQ Angular SDK</h1>
    </div>
    <div class="flex">
      <ul class="flex items-center text-[14px]">
        <li class="active:text-blue-700 active:underline"><a routerLink="/" ariaCurrentWhenActive="page" class="px-3 mx-1">SDK</a></li>
        <li class="active:text-blue-700 active:underline"><a routerLink="/components" ariaCurrentWhenActive="page" class="px-3 mx-1">Components</a></li>
      </ul>
    </div>
</nav>
  `,
  standalone: true,
  imports: [CommonModule,RouterLink,RouterLinkActive],
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent {

}

<p>navbar works!</p>

// sdk/ui/svelte/docs/src/routes/Navbar.svelte
<script>
    import logo from '$lib/images/logo.png'
</script>

<nav>
    <div class='boxyhq-logo'>
        <div>
            <img src={logo} alt="BoxyHQ logo" width="40" height="40"/>
        </div>
       <div class='nav-title'>
        <h1>BoxyHQ Svelte SDK<h1>
       </div>
    </div>
    <div >
        <ul class='nav-links'>
            <li>
                <a href='/'>SDK</a> 
            </li>
            <li>
                <a href='/components'>Components</a> 
            </li>
        </ul>   
    </div>
</nav>    

<style>
nav {
    display: flex;
    justify-content: space-between;
    align-items: center;
    height: 65px;
    font-size: 12px;
    padding: 5px 40px;
    margin-bottom: 15px;
    box-shadow: 0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02);
}


.boxyhq-logo {
  display: flex;
  justify-content: center;
  align-items: center;
}

.nav-links{
    display:flex;
}

.nav-links a:active {
    color: blue;
    text-decoration: underline;
}

.nav-title {
    font-size: 14px;
    font-weight: normal;
    margin-left: 15px;
}

ul {
    list-style-type: none;  
}

li a {
    text-decoration: none;
    padding:0 10px;
    font-size: 15px;
    font-family: sans-serif;
    cursor: pointer;
    color: black;
}
</style>
