// sdk/ui/vue/docs/src/views/Components.vue
<script setup>
import { Login } from '@boxyhq/vue3-ui';
</script>

<template>
  <main class="hero-body-components">
    <div class="body-components">
      <div class="login-with-custom-styles">
        <Login @onSubmit="onSubmitButton" :innerProps="{ input: { type: 'email' } }" inputLabel="Team Domain *" buttonText="Login with SSO" placeholder="contoso@boxyhq.com" :classNames="{ button: 'btn', input: 'inp'}" :styles="{ input: { borderColor: '#ebedf0' }, button: { padding: '.85rem' } }"/>
        <h2 class="hero-title">Login Component with custom styling</h2>
        <h2 class="hero-description">Refer the code below to see the passed props. Also supported is the passing of style attribute for each inner element (Note that inline style will override other styles).</h2>
        <button @click="toggleCodeSnippet('loginWithCustomStylingActive')" class="btn-toggle">Hide code</button>
        <div v-if="loginWithCustomStylingActive">
        <pre><code class="language-js">
{{ loginWithCustomStyling }}
        </code></pre>
        </div>
      </div>
      <div class="login-default-styles">
      <Login :styles="{input: { border: '1px solid darkcyan' }}" @onSubmit="onSubmitButton" inputLabel="Team domain *" placeholder="contoso@boxyhq.com" />
      <h2 class="hero-title">Login Component with default styles</h2>
      <h2 class="hero-description">If classNames prop is not passed in, then default styling will be applied. Also supported is the passing of style attribute for each inner element (Note that inline style will override other styles).</h2>
      <button @click="toggleCodeSnippet('loginDefaultStylesActive')" class="btn-toggle">Hide code</button>
      <div v-if="loginDefaultStylesActive" class="component-code">
        <pre><code class="language-js">        

{{ defaultStylesComponentCode }}
      </code></pre>
      </div>
    </div>
    <div class="login-without-input">
      <Login class="hero" ssoIdentifier="some-identifier" buttonText="SIGN IN WITH SSO" />
      <h2 class="hero-title">Login Component without input display</h2>
      <h2 class="hero-description">Here we pass the ssoIdentifier directly instead of taking a user input.</h2>
      <button @click="toggleCodeSnippet('loginWithoutInputIsActive')" class="btn-toggle">Hide code</button>
      <div v-if="loginWithoutInputIsActive">
      <pre><code class="language-js">
{{ loginWithoutInput }}  
      </code></pre></div>
    </div>
    <div class="login-with-failing-onsubmit">
      <Login @onSubmit="onSubmitButton" :errorMessage="this.errorOnSubmit" class="child" inputLabel="Team domain *" placeholder="contoso@boxyhq.com" />
      <h2 class="hero-title">Login Component with failing onSubmit</h2>
      <h2 class="hero-description">If error object is returned with the error message, the message would be displayed inline.</h2>
      <button @click="toggleCodeSnippet('loginWithFailingOnSubmitActive')" class="btn-toggle">Hide code</button>
      <div v-if="loginWithFailingOnSubmitActive">
      <pre><code class="language-js">
{{ loginWithFailingOnSubmit }}
      </code></pre>
      </div>
    </div>
    </div>
  </main>
</template>

<script>
import Prism from 'prismjs';
import 'prismjs/themes/prism.css';
import 'prismjs/components/prism-jsx';

export default {
  data() {
    return {
      showCodeSnippet: true,
      loginWithoutInputIsActive: true,
      loginDefaultStylesActive: true,
      loginWithFailingOnSubmitActive: true,
      loginWithCustomStylingActive: true,
      errorOnSubmit: { error: {message: "Invalid team domain"}},
      loginWithFailingOnSubmit:"<template>\n  <Login\n    :@onSubmit='async (ssoIdentifier) => {\n        // Initiate SSO flow here\n     }',\n    :errorMessage='{ error: { message:'Invalid team domain' } }',\n    inputLabel='Team domain *',\n    placeholder='contoso@boxyhq.com',\n  /> \n</template>\n\n<script>\nimport { Login } from '@boxyhq/vue3-ui';\n\nexport default {\n  name:'Demo4'\n}\n< /script>",
      loginWithCustomStyling:"<template>\n  <Login\n    :@onSubmit='async (ssoIdentifier) => {\n       // initiate  the SSO flow here\n     }'\n    :styles='{ input: { borderColor: '#ebedf0' }, button: { padding: '.85rem' } }',\n    :classNames='{button: 'btn', input: 'inp'}'\n    inputLabel='Team domain *',\n    placeholder='contos@boxyhq.com',\n    buttonText='Login with SSO'\n    :innerProps='{input: { type: 'email' }}'\n   /> \n</template>\n\n<script>\nimport { Login } from '@boxyhq/vue3-ui';\n@import url('./demo1.css');\n\nexport default {\n  name:'Demo1'\n}\n< /script>",
      defaultStylesComponentCode:"<template>\n  <Login\n    :styles='{ input: { border: '1px solid darkcyan' } }',\n    inputLabel='Team domain *',\n    placeholder='contos@boxyhq.com',\n   /> \n</template>\n\n<script>\nimport { Login } from '@boxyhq/vue3-ui';\n\nexport default {\n  name:'Demo2'\n}\n< /script>",
      defaultStylesCode:"<Login\n      :styles='{ input: { border: '1px solid darkcyan' } }',\n      inputLabel='Team domain *',\n      placeholder='contos@boxyhq.com'\n    />",
      loginWithoutInput:"<template>\n  <Login\n    :@onSubmit='async (ssoIdentifier) => {\n       // initiate  the SSO flow here\n     }',\n    ssoIdentifier='some-identifier',\n    buttonText='SIGN IN WITH SSO',\n  /> \n</template>\n\n<script>\nimport { Login } from '@boxyhq/vue3-ui';\n\nexport default {\n  name:'Demo3'\n}\n< /script>",
    };
  },
  methods: {
    onSubmitButton() {
      console.log('Button submission initiated');
    },
    toggleCodeSnippet(propertyName) {
      this[propertyName] = !this[propertyName];
    },
    toggleButton() {
      this.showCodeSnippet = !this.showCodeSnippet;
    },
  },
  mounted() {
    Prism.highlightAll();
  },
  created() {
    this.$emit('onSubmit');
  }
};
</script>

// sdk/ui/angular/projects/docs/src/app/components/components.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginComponent } from '@boxyhq/angular-ui';
import { NavbarComponent } from '../navbar/navbar.component';
import { PrismService } from '../services/prism.services';
import Prism from 'prismjs';

@Component({
  selector: 'app-components',
  template: `
    <app-navbar></app-navbar>
    <div class="my-5 px-10">
      <div class="border-[rgba(5, 5, 5, 0.1)] border-[1px] p-10">
        <sso-login
          (onSubmit)="onSubmit()"
          [styles]="customStyles"
          [classNames]="customStyleClasses"
          [inputLabel]="'Team domain*'"
          [placeholder]="'contoso@boxyhq.com'"
          [buttonText]="'Login with SSO'"></sso-login>
        <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">Login with custom styling</h1>
        <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
          Refer the code below to see the passed props. Also supported is the passing of style attribute for
          each inner element (Note that inline style will override other styles).
        </h1>
        <button
          (click)="toggleButton(displayCustomStyle, 'displayCustomStyle')"
          class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
          Hide code
        </button>
        <div *ngIf="displayCustomStyle">
          <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{customStylingCode}}
          </code>
        </pre>
        </div>
      </div>

      <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10">
        <sso-login
          [styles]="defaultStylesCode"
          [inputLabel]="'Team domain*'"
          [classNames]="componentClassnames"
          [placeholder]="'contoso@boxyhq.com'"
          [buttonText]="'Login with SSO'"></sso-login>
        <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
          Login Component with default styles
        </h1>
        <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
          If classNames prop is not passed in, then default styling will be applied. Also supported is the
          passing of style attribute for each inner element (Note that inline style will override other
          styles).
        </h1>
        <button
          (click)="toggleButton(displayDeafaultStyle, 'displayDeafaultStyle')"
          class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
          Hide code
        </button>
        <div *ngIf="displayDeafaultStyle">
          <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{defaulatStylesCode}}
          </code>
        </pre>
        </div>
      </div>

      <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10">
        <sso-login
          [ssoIdentifier]="'some-sso-identifier'"
          [classNames]="componentClassnames"
          [styles]="defaultStylesCode"
          [buttonText]="'SIGN IN WITH SSO'"></sso-login>
        <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
          Login Component without input display
        </h1>
        <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
          Here we pass the ssoIdentifier directly instead of taking a user input.
        </h1>
        <button
          (click)="toggleButton(displayLoginWithouInput, 'displayLoginWithouInput')"
          class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
          Hide code
        </button>
        <div *ngIf="displayLoginWithouInput">
          <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{loginWithoutInputCode}}
          </code>
        </pre>
        </div>
      </div>

      <div class="border-[rgba(5, 5, 5, 0.1)] my-5 border-[1px] p-10">
        <sso-login
          [classNames]="componentClassnames"
          [styles]="onsubmitFailStylesCode"
          [inputLabel]="'Team domain*'"
          [placeholder]="'contoso@boxyhq.com'"
          [errorMessage]="errorMessage"
          [buttonText]="'SIGN IN WITH SSO'"></sso-login>
        <h1 class="mb-2 mt-4 border-b-[1px] border-[#eaecef] pb-[0.5em]">
          Login Component with failing onSubmit
        </h1>
        <h1 class="border-b-[1px] border-dashed border-[#eaecef] pb-[0.5em]">
          If error object is returned with the error message, the message would be displayed inline.
        </h1>
        <button
          (click)="toggleButton(displayFailingOnSubmit, 'displayFailingOnSubmit')"
          class="my-[1em] rounded-md bg-[#0070f3] px-[0.7em] py-[0.5em] font-medium text-white">
          Hide code
        </button>
        <div *ngIf="displayFailingOnSubmit">
          <pre aria-hidden="true" class="pre">
          <code #codeContent [ngClass]="['code', 'language-' + codeType]">
{{failingOnSubmitCode}}
          </code>
        </pre>
        </div>
      </div>
    </div>
  `,
  standalone: true,
  imports: [CommonModule, LoginComponent, NavbarComponent],
  styleUrls: ['./components.component.css'],
})
export class ComponentsComponent {
  componentStyles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
    },
  };

  componentClassnames = {
    container: '',
  };

  customStyleClasses = {
    button: 'btn',
    input: 'inp',
  };

  customStyles = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      width: '50%',
    },
    input: {
      borderColor: '#ebedf0',
    },
    button: {
      padding: '.85rem',
      marginLeft: '0',
    },
  };

  errorMessage = {
    error: {
      message: 'Invalid team domain',
    },
  };

  defaultStylesCode = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      width: '50%',
    },
    input: { border: '1px solid darkcyan' },
  };

  onsubmitFailStylesCode = {
    container: {
      display: 'flex',
      flexDirection: 'column',
      width: '50%',
    },
  };

  onSubmit = async () => {
    console.log('Button clicked');
  };

  codeType = 'javascript';
  highlighted: false;

  displayCustomStyle = true;
  displayDeafaultStyle = true;
  displayLoginWithouInput = true;
  displayFailingOnSubmit = true;

  toggleButton(propValue, propName) {
    if (propName === 'displayCustomStyle') {
      this.displayCustomStyle = !propValue;
    } else if (propName === 'displayDeafaultStyle') {
      this.displayDeafaultStyle = !propValue;
    } else if (propName === 'displayLoginWithouInput') {
      this.displayLoginWithouInput = !propValue;
    } else if (propName === 'displayFailingOnSubmit') {
      this.displayFailingOnSubmit = !propValue;
    } else {
      return;
    }
  }

  customStylingCode = `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginTrialComponent } from '@boxyhq/angular-ui';
  
  @Component({
    selector: "my-component, MyComponent",
    template: '
    <sso-login
      [classNames]="componentClassnames"
      [styles]="componentStyles"
      [buttonText]="'Login with SSO'"
      [inputLabel]="'Team Domain*'"
      [placeholder]="'contoso@boxyhq.com'"
      (onSubmit)="onSubmitButton()"></sso-login>
    ',
    standalone: true,
    imports: [CommonModule, LoginComponent],
    styleUrls: ['./my-component.component.css'],
  })
  export class MyComponent{
    componentStyles = {
      input: { borderColor: '#ebedf0' },
      button: { padding: '.85rem' }
    }

    componentClassnames = {
      button:'btn',
      input: 'inp
    };
  
    async function onSubmitButton() {
      // initiate the SSO flow here
   };
  }`;

  defaulatStylesCode = `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginTrialComponent } from '@boxyhq/angular-ui';
    
  @Component({
    selector: "my-component, MyComponent",
    template: '
    <sso-login
      [styles]="componentStyles"
      [inputLabel]="'Team Domain*'"
      [placeholder]="'contoso@boxyhq.com'"
      (onSubmit)="onSubmitButton()"></sso-login>
    ',
    standalone: true,
    imports: [CommonModule, LoginComponent],
    styleUrls: ['./my-component.component.css'],
  })
  export class MyComponent{
    componentStyles = {
      input: { border: '1px solid darkcyan' },
    }

    async function onSubmitButton() {
      // initiate the SSO flow here
    };
  }`;

  loginWithoutInputCode = `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginTrialComponent } from '@boxyhq/angular-ui';
      
  @Component({
    selector: "my-component, MyComponent",
    template: '
      <sso-login
          [buttonText]="'SIGN IN WITH SSO'"
          [ssoIdentifier]="'some-identifier'"
          (onSubmit)="onSubmitButton()"></sso-login>
      ',
    standalone: true,
    imports: [CommonModule, LoginComponent],
    styleUrls: ['./my-component.component.css'],
  })
  export class MyComponent{
    async function onSubmitButton() {
      / initiate the SSO flow here
    };
  }`;

  failingOnSubmitCode = `import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LoginTrialComponent } from '@boxyhq/angular-ui';
            
  @Component({
    selector: "my-component, MyComponent",
    template: '
        <sso-login
          [buttonText]="'SIGN IN WITH SSO'"
          [ssoIdentifier]="'some-identifier'"
          (onSubmit)="onSubmitButton()"></sso-login>
        ',
    standalone: true,
    imports: [CommonModule, LoginComponent],
    styleUrls: ['./my-component.component.css'],
  })
  export class MyComponent{
    async function onSubmitButton() {
      // initiate the SSO flow here
    };
  }`;

  constructor(private prismService: PrismService) {}

  ngAfterContentChecked() {
    Prism.highlightAll();
  }

  ngAfterViewChecked() {
    Prism.highlightAll();
  }

  ngOnDestroy() {
    Prism.highlightAll();
  }
}

<p>Welcome to the components page!</p>
